-- Backfills the new NL columns for all 53 GETH cards, ported 1:1 from the web app's
-- lib/card-content-translations.ts (description/recognitionSentence) and the
-- cardTitleTranslations map in lib/cards.ts (title). No new translation work — this is a
-- straight data port so mobile's "give a card" flow can stop showing raw English text to
-- Dutch-locale users.

alter table card_library
  add column if not exists title_nl text,
  add column if not exists description_nl text,
  add column if not exists recognition_sentence_nl text;

update card_library set
  title_nl = case qr_slug
    when 'luisteraar' then 'Luisteraar'
    when 'helder' then 'Helder'
    when 'eerlijk' then 'Eerlijk'
    when 'verbinder' then 'Verbinder'
    when 'empathisch' then 'Empathisch'
    when 'overtuigend' then 'Overtuigend'
    when 'gastvrij' then 'Gastvrij'
    when 'inspirerend' then 'Inspirerend'
    when 'diplomatiek' then 'Diplomatiek'
    when 'leidend' then 'Leidend'
    when 'nieuwsgierig' then 'Nieuwsgierig'
    when 'enthousiast' then 'Enthousiast'
    when 'geruststeller' then 'Geruststeller'
    when 'vernieuwend' then 'Vernieuwend'
    when 'avontuurlijk' then 'Avontuurlijk'
    when 'humor' then 'Humor'
    when 'visionair' then 'Visionair'
    when 'onderzoekend' then 'Onderzoekend'
    when 'authentiek' then 'Authentiek'
    when 'opmerkzaam' then 'Opmerkzaam'
    when 'verzorgd' then 'Verzorgd'
    when 'oplosser' then 'Oplosser'
    when 'intuitief' then 'Intuitief'
    when 'improvisator' then 'Improvisator'
    when 'uitdager' then 'Uitdager'
    when 'dromer' then 'Dromer'
    when 'doelgericht' then 'Doelgericht'
    when 'analytisch' then 'Analytisch'
    when 'betrouwbaar' then 'Betrouwbaar'
    when 'strategisch' then 'Strategisch'
    when 'nauwkeurig' then 'Nauwkeurig'
    when 'daadkrachtig' then 'Daadkrachtig'
    when 'leergierig' then 'Leergierig'
    when 'organisator' then 'Organisator'
    when 'veerkrachtig' then 'Veerkrachtig'
    when 'resultaatgericht' then 'Resultaatgericht'
    when 'proactief' then 'Proactief'
    when 'besluitvaardig' then 'Besluitvaardig'
    when 'kritisch' then 'Kritisch'
    when 'zorgzaam' then 'Zorgzaam'
    when 'loyaal' then 'Loyaal'
    when 'teamspeler' then 'Teamspeler'
    when 'vertrouwenspersoon' then 'Vertrouwenspersoon'
    when 'ondersteunend' then 'Ondersteunend'
    when 'respectvol' then 'Respectvol'
    when 'dankbaar' then 'Dankbaar'
    when 'inclusief' then 'Inclusief'
    when 'geduldig' then 'Geduldig'
    when 'beschermend' then 'Beschermend'
    when 'energiek' then 'Energiek'
    when 'aanwezig' then 'Aanwezig'
    when 'waarderend' then 'Waarderend'
    when 'open-categorie' then 'Open Categorie'
    else title_nl
  end,
  description_nl = case qr_slug
    when 'luisteraar' then 'Jij geeft mensen de ruimte om volledig hun verhaal te doen zonder te onderbreken. Door jouw aandacht voelen mensen zich gehoord en serieus.'
    when 'helder' then 'Jij vertaalt complexe situaties naar begrijpelijke taal, afgestemd op de ander. Jij weet precies hoe je iets op de juiste manier kunt overbrengen, zodat het echt landt.'
    when 'eerlijk' then 'Jij benoemt wat nodig is op een duidelijke en respectvolle manier. Door jouw eerlijkheid ontstaat helderheid en weten anderen waar ze aan toe zijn.'
    when 'verbinder' then 'Jij ziet wat mensen met elkaar gemeen hebben en brengt hen op een natuurlijke manier samen. Daardoor ontstaan verbindingen die het werk en de samenwerking versterken.'
    when 'empathisch' then 'Jij voelt aan wat iemand nodig heeft, eventueel ook zonder dat het uitgesproken wordt. Jouw medeleven en vermogen om je in een ander te verplaatsen maakt de samenwerking menselijk.'
    when 'overtuigend' then 'Jij weet mensen mee te nemen in jouw verhaal zonder te forceren. Je combineert logica met gevoel en daardoor ontstaat beweging vanzelf.'
    when 'gastvrij' then 'Jij zorgt ervoor dat mensen zich welkom voelen vanaf het eerste moment. Jij hebt een natuurlijk gevoel voor wat iemand nodig heeft om zich op zijn gemak te voelen.'
    when 'inspirerend' then 'Jij geeft mensen met jouw woorden en energie zin om dingen op te pakken of door te pakken. Na een gesprek met jou voelt er vaak meer mogelijk.'
    when 'diplomatiek' then 'Jij voelt aan wanneer een gesprek lastig wordt en weet dan precies de juiste, verzachtende woorden te kiezen. Daardoor zorg jij dat situaties niet escaleren en iedereen betrokken blijft.'
    when 'leidend' then 'Jij geeft helder richting zonder te overheersen. Wanneer anderen twijfelen, bied jij handvatten en laat je zien welke mogelijkheden er zijn om verder te kunnen.'
    when 'nieuwsgierig' then 'Jij wilt graag alle kanten van een verhaal begrijpen. Door jouw vragen ontstaat er verdieping en krijgen mensen een completer beeld van wat er speelt.'
    when 'enthousiast' then 'Jij brengt leven in een gesprek. Jouw enthousiasme werkt aanstekelijk.'
    when 'geruststeller' then 'Jij hebt het vermogen om mensen tot rust te brengen in onzekere momenten. Jouw woorden en aanwezigheid geven kalmte aan wie dat nodig heeft.'
    when 'vernieuwend' then 'Jij denkt out of the box. Jouw ideeen openen vensters die anderen nog niet zagen. Jij geeft een frisse, innovatieve blik op wat er mogelijk kan zijn.'
    when 'avontuurlijk' then 'Jij omarmt het onbekende. Waar anderen voorzichtig worden, zie jij een kans. Jouw bereidheid om risico te nemen opent nieuwe wegen voor het hele team.'
    when 'humor' then 'Jij brengt plezier, luchtigheid en positiviteit in wat dreigt vast te lopen. Dankzij jouw humor voelt het prettig om mee te doen.'
    when 'visionair' then 'Jij ziet voor je wat er mogelijk is op langere termijn en weet daar richting aan te geven. Daarmee help je anderen om verder te kijken dan vandaag.'
    when 'onderzoekend' then 'Jij stelt scherpe vragen en ontdekt inzichten die anderen helpen betere keuzes te maken.'
    when 'authentiek' then 'Jij laat je niet leiden door wat gangbaar is. In wat jij maakt of zegt zit iets eigens dat herkenbaar en onderscheidend is.'
    when 'opmerkzaam' then 'Jij ziet wat anderen niet zien. Puur omdat jij zo kijkt. Details, sfeer, wat er onder de oppervlakte speelt. Niets gaat aan jou voorbij.'
    when 'verzorgd' then 'Jij levert nooit half werk. Wat jij maakt ziet er goed uit. Dat gevoel voor kwaliteit straalt af op alles wat jij aanraakt.'
    when 'oplosser' then 'Jij ziet problemen als uitnodigingen om anders te kijken. Waar anderen vastlopen, ontdek jij vaak een creatieve doorgang.'
    when 'intuitief' then 'Jij durft te vertrouwen op je gevoel. Jouw intuitie is geen losse ingeving, maar een gevoeligheid voor wat klopt in het moment.'
    when 'improvisator' then 'Jij blijft kalm als plannen veranderen. Jij maakt van onverwachte situaties iets bruikbaars.'
    when 'uitdager' then 'Jij daagt constructief de status quo uit. Jij stelt de vraag "maar waarom eigenlijk?" en die vraag zorgt voor inzicht.'
    when 'dromer' then 'Jij durft groot te denken. Jouw dromen zijn de zaadjes van de toekomst voor jou en voor anderen.'
    when 'doelgericht' then 'Jij weet waar je naartoe werkt en houdt scherp wat er echt toe doet. Daardoor help je anderen om focus te houden op het doel.'
    when 'analytisch' then 'Jij ziet structuur waar anderen chaos zien. Jij ontleedt problemen met precisie en vindt de kern van de zaak snel.'
    when 'betrouwbaar' then 'Wat jij zegt, doe jij. Altijd. Jouw betrouwbaarheid is het fundament waarop anderen durven bouwen.'
    when 'strategisch' then 'Jij denkt drie stappen vooruit. Jij ziet patronen en kansen die anderen nog niet zien, en geeft inzichten die op lange termijn kloppen.'
    when 'nauwkeurig' then 'Jij mist niets. Jouw oog voor detail beschermt de kwaliteit, ook als anderen al tevreden zouden zijn.'
    when 'daadkrachtig' then 'Jij komt in beweging waar anderen nog afwegen. Door jouw daadkracht ontstaat er tempo en wordt het voor anderen makkelijker om ook mee te gaan.'
    when 'leergierig' then 'Jij groeit bewust. Jij zoekt feedback op, omarmt ongemak en maakt van elke fout een stap vooruit.'
    when 'organisator' then 'Jij brengt orde in complexiteit. Jouw vermogen om te structureren maakt het voor iedereen mogelijk om te presteren.'
    when 'veerkrachtig' then 'Jij bent stabiel als het tegenzit. Tegenslagen breng jij in perspectief en jij herpakt je snel, waardoor het niet als een grote tegenslag aanvoelt.'
    when 'resultaatgericht' then 'Jij houdt het einddoel scherp voor ogen. Jij weet het verschil tussen druk zijn en productief zijn, en kiest altijd voor wat echt bijdraagt aan het doel.'
    when 'proactief' then 'Jij wacht niet af. Jij ziet wat er nodig is voordat anderen het opmerken, en handelt al voordat er gevraagd wordt.'
    when 'besluitvaardig' then 'Jij neemt beslissingen, ook als niet alles duidelijk is. Jij weet dat niet beslissen ook een keuze kan zijn en neemt verantwoordelijkheid voor je keuze.'
    when 'kritisch' then 'Jij accepteert niet zomaar wat voor je wordt neergelegd. Jouw kritische blik beschermt de kwaliteit en zorgt dat het beste naar boven komt.'
    when 'zorgzaam' then 'Jij let op mensen, niet vanuit plicht, maar vanuit echte aandacht. Jij merkt op wanneer het minder goed gaat, voordat iemand het zelf heeft gezegd.'
    when 'loyaal' then 'Jij blijft staan voor de mensen om je heen, juist wanneer het moeilijk wordt. Je verlaat mensen niet wanneer het tegenzit, maar kiest voor trouw, vertrouwen en echte verbondenheid.'
    when 'teamspeler' then 'Jij plaatst het belang van het team voorop. Jij deelt credits, ondersteunt anderen en draagt bij aan het gezamenlijk doel.'
    when 'vertrouwenspersoon' then 'Mensen kiezen jou als ze iets vertrouwelijks moeten delen. Jij bewaart dat vertrouwen zorgvuldig en discreet.'
    when 'ondersteunend' then 'Jij bent er voor anderen op het moment dat het telt. Jij helpt en geeft steun wanneer ze dat echt nodig hebben.'
    when 'respectvol' then 'Jij respecteert de grenzen, het tempo en de perspectieven van anderen. Jij legt niets op, maar schept ruimte zodat de ander zichzelf kan zijn.'
    when 'dankbaar' then 'Jij ziet wat anderen bijdragen en spreekt dat uit. Jij laat mensen weten dat hun bijdrage telt, en dat verandert de sfeer.'
    when 'inclusief' then 'Jij zorgt ervoor dat niemand buitengesloten wordt. Jij trekt stille stemmen naar voren en maakt ruimte voor wie normaal geen ruimte krijgt.'
    when 'geduldig' then 'Jij geeft mensen de tijd die ze nodig hebben. Jij dwingt geen tempo op dat niet bij hen past en dat maakt samenwerken veilig.'
    when 'beschermend' then 'Jij staat op voor anderen als dat nodig is. Jij laat niet toe dat mensen weggezet of genegeerd worden, zacht maar standvastig. Jij zorgt voor iemands welzijn.'
    when 'energiek' then 'Jij brengt leven in een ruimte. Jouw aanwezigheid tilt de energie van het team omhoog en zorgt ervoor dat we doorgaan op het moment dat anderen afhaken.'
    when 'aanwezig' then 'Jij bent echt aanwezig. Geen halve aandacht, geen afleiding, jij richt je volledig op de mens voor je.'
    when 'waarderend' then 'Jij ziet het goede in mensen. Jouw waardering is geen complimentje, het is een spiegel die mensen groter laat zijn. Jij maakt iemands bijdrage zichtbaar door te waarderen. Deze kwaliteit is de basis voor een goede werkomgeving, goede medewerkers en een goed resultaat.'
    when 'open-categorie' then 'Vul de te waarderen kwaliteit in:'
    else description_nl
  end,
  recognition_sentence_nl = case qr_slug
    when 'luisteraar' then 'Jij luisterde naar mij vandaag, oprecht geinteresseerd, zonder te onderbreken. Ik voelde me echt gehoord.'
    when 'helder' then 'Dankzij jouw duidelijke uitleg begreep ik wat er precies bedoeld werd.'
    when 'eerlijk' then 'Ik waardeer dat je het eerlijk benoemde. Dat gaf duidelijkheid en hielp ons een betere keuze maken.'
    when 'verbinder' then 'Jij brengt mensen bij elkaar die elkaar verder helpen en versterken. Het is je tweede natuur.'
    when 'empathisch' then 'Bij jou hoef ik niets uit te leggen, jij voelt de sfeer aan en hebt begrip voor de situatie. Ik voel mij echt begrepen.'
    when 'overtuigend' then 'Jij overtuigde me vandaag niet met druk, maar met inzicht. Daardoor kon ik volmondig ja zeggen waardoor het echt als mijn keuze voelde.'
    when 'gastvrij' then 'Jij zorgde er vandaag voor dat ik me welkom voelde. Dat is niet vanzelfsprekend en zorgt ervoor dat ik hier graag naartoe kom.'
    when 'inspirerend' then 'Na ons gesprek kreeg ik nieuwe energie om door te pakken. Jij liet me inzien dat het mogelijk is.'
    when 'diplomatiek' then 'De manier waarop jij de juiste woorden koos, hield het gesprek rustig en zorgde dat iedereen bleef luisteren.'
    when 'leidend' then 'Jij gaf ons precies de duidelijkheid en handvatten die we nodig hadden om verder te kunnen.'
    when 'nieuwsgierig' then 'Jouw vragen lieten me verder kijken dan ik zelf zou zijn gegaan. Daardoor begreep ik de situatie pas echt.'
    when 'enthousiast' then 'Elke keer als jij praat, raak ik enthousiast en krijg ik zin om mee te helpen. Dat is een gave die jij gewoon hebt.'
    when 'geruststeller' then 'Jij zorgde ervoor dat ik rustig werd juist toen ik het nodig had. Door jou voel ik me weer op mijn gemak.'
    when 'vernieuwend' then 'Jouw idee bracht precies de frisse blik die nodig was, dat heeft echt iets opgeleverd.'
    when 'avontuurlijk' then 'Jij durfde vandaag een stap te zetten die wij allemaal spannend vonden. Dankzij jou komen we verder.'
    when 'humor' then 'Jij bracht precies de energie die nodig was om het prettig te laten voelen en dat voelde ik direct.'
    when 'visionair' then 'Jij liet me zien waar we in de toekomst kunnen staan. Dat maakte het ineens concreet en tastbaar.'
    when 'onderzoekend' then 'Dat jij verder keek dan de rest en doorvroeg, hielp ons een beter besluit te nemen. Zonder jou hadden we dat gemist.'
    when 'authentiek' then 'Ik herken jou direct in wat jij maakt, doet of zegt. Jij brengt altijd iets dat echt van jou is.'
    when 'opmerkzaam' then 'Jij merkte vandaag iets op wat de rest had gemist. Dankzij jou hebben we het niet laten liggen.'
    when 'verzorgd' then 'Wat jij vandaag maakte straalde kwaliteit uit en was tot in de puntjes verzorgd. Dat is jouw standaard.'
    when 'oplosser' then 'Jij zag een kans waar wij vooral een probleem zagen. Waardevol dat jij dat zag.'
    when 'intuitief' then 'Je voelde feilloos aan wat hier nodig was, nog voordat alles was uitgesproken.'
    when 'improvisator' then 'Dat jij zo soepel schakelde, zorgde ervoor dat wij ook rustig konden blijven.'
    when 'uitdager' then 'Jij liet me vandaag mijn eigen aannames zien. Dit was ongemakkelijk maar verhelderend en precies wat ik nodig had.'
    when 'dromer' then 'Jouw droom van vandaag gaf mij moed om ook iets groots te durven denken.'
    when 'doelgericht' then 'Jij hield ons bij de kern toen wij dreigden af te dwalen. Dankzij jou hielden we het doel in zicht.'
    when 'analytisch' then 'Jouw analyse bracht rust in iets wat voor ons ondoorzichtig was. Helder en direct, dat gaf mij vertrouwen.'
    when 'betrouwbaar' then 'Ik kan op jou bouwen; dat geeft stabiliteit voor mij, voor het team en voor het resultaat.'
    when 'strategisch' then 'Jij zag vandaag wat deze beslissing over twee jaar betekent.'
    when 'nauwkeurig' then 'Jij zag wat wij niet zagen. En daardoor werd ons werk echt goed.'
    when 'daadkrachtig' then 'Dat jij gewoon begon, gaf ons allemaal het zetje dat we nodig hadden.'
    when 'leergierig' then 'De manier waarop jij omging met die feedback liet mij zien hoe groei ontstaat en je van fouten kunt leren.'
    when 'organisator' then 'Dankzij jou wist iedereen vandaag wat hij of zij moest doen. Dat is van onschatbare waarde.'
    when 'veerkrachtig' then 'De manier waarop jij je herpakte, inspireerde mij. Jij liet zien dat je je niet laat stoppen.'
    when 'resultaatgericht' then 'Jij bracht focus op wat echt bijdraagt. Dankzij jou maken we echte stappen.'
    when 'proactief' then 'Jij had dit al geregeld voor ik er uberhaupt aan had gedacht. Dat geeft rust.'
    when 'besluitvaardig' then 'Jij nam een besluit toen wij bleven twijfelen. Dankzij jou konden we verder.'
    when 'kritisch' then 'Doordat jij durfde te vragen, kwamen we op tijd tot inzicht. Zonder jou hadden we dat gemist.'
    when 'zorgzaam' then 'Dankzij jouw zorgzaamheid voelde ik me gezien op een moment dat ik dat hard nodig had.'
    when 'loyaal' then 'Dat jij er was, ook toen het moeilijk was, betekent meer dan jij weet. Jouw loyaliteit gaf mij vertrouwen, stabiliteit en de zekerheid dat ik op je kan bouwen.'
    when 'teamspeler' then 'Jij hield vandaag het team sterk zonder zelf op de voorgrond te hoeven staan. Juist daardoor kon iedereen beter presteren.'
    when 'vertrouwenspersoon' then 'Ik kan jou dingen vertellen die ik niemand anders vertel. Dat vertrouwen is niet vanzelfsprekend en ik ben blij dat jij er bent.'
    when 'ondersteunend' then 'Jij was er voor mij, dat was precies genoeg. Jij gaf me rust en vertrouwen toen ik het nodig had.'
    when 'respectvol' then 'Jij gaf mij vandaag de ruimte om op mijn eigen manier bij te dragen. Dat voelde als oprechte samenwerking.'
    when 'dankbaar' then 'Dat jij dat vandaag hardop zei, waardeer ik. Het geeft me energie om door te gaan.'
    when 'inclusief' then 'Jij zorgde er vandaag voor dat ik er ook bij hoorde. Dat geeft me het gevoel van gelijkwaardigheid en dat ik iets bijdraag.'
    when 'geduldig' then 'Dat jij mij de tijd gaf zonder ongeduld, nam de druk weg. Daardoor kon ik laten zien wat ik in huis heb.'
    when 'beschermend' then 'Dat jij voor mij opkwam, waardeer ik. Jij zorgde ervoor dat ik me veilig voelde.'
    when 'energiek' then 'Elke keer als jij er bent, is de sfeer beter. Dat is puur jouw bijdrage. Jouw energie werkt aanstekelijk en brengt enthousiasme.'
    when 'aanwezig' then 'Jij was er vandaag volledig, en ik voelde dat. Dat maakt het verschil. Volle aandacht is het beste wat je iemand kunt geven.'
    when 'waarderend' then 'Dat je mijn bijdrage waardeert, geeft me het gevoel dat ik gezien word. Dit geeft me kracht, positiviteit en energie.'
    when 'open-categorie' then 'Maak je eigen erkenningszin:'
    else recognition_sentence_nl
  end;
